trigger:
  tags:
    include:
    - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  condition: or(eq( variables['Agent.OS'], 'Linux' ), eq( variables['Agent.OS'], 'Darwin' )) 
  displayName: install rust linux / macOS

- powershell: choco install rustup.install
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: install rust windows

- bash: |
    cargo build --release
  displayName: 'cargo build'

- task: CopyFiles@2
  displayName: 'copy bin files Linux/macOS'
  condition: or(eq( variables['Agent.OS'], 'Linux' ), eq( variables['Agent.OS'], 'Darwin' ))
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target/release/'
    Contents: 'rlget'
    TargetFolder: '$(Build.BinariesDirectory)/$(Agent.OS)/'
  
- task: CopyFiles@2
  displayName: 'copy bin files Windows'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target/release/'
    Contents: 'rlget.exe'
    TargetFolder: '$(Build.BinariesDirectory)/$(Agent.OS)/'


- bash: |
    rm -r target
  displayName: 'remove target'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
